### ISSUE TITLE
column and field access to tabular data

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#10]
A lot of Fury output comes in a tabular format, and it is possible to use the `--raw` flag to show just the index column from the table. It would be useful to be able to show other columns, for example by providing the `--column` option (which would take a lowercase column name as an argument) and/or a `--row` option, which would take the index for the row, and return just a single field.

**Comment by martinpallmann** [comment]
couldn't a user not  just use `awk`, `head` and `tail` to have the same result?

**Comment by propensive** [comment]
Potentially, though not so easily. It would also not be resilient to changes in the output format, and you would need to remove the ANSI color highlighting, too.
