### ISSUE TITLE
Generation of the BSP config fails if Fury is not present in the classpath

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1040]
The code that generates the configuration file for using Fury as a BSP server assumes that `which fury` will always print a valid path and exit with code 0. However, this assumption doesn't hold on a clean system, on which Fury has never been installed before. Due to BSP configuration being generated by the `layer extract` command (and also `layer init`), installation on a clean system will always fail.

This issue was introduced by PR #996 and caused failures in PR #1032.

The hack introduced in commit 7273f7b6618f39d763c42142e191e99b947ecd2c fixes the installation process, but does not solve the issue completely.

**Comment by propensive** [comment]
The problem, if I remember correctly, is that a running version of Fury can't actually tell the command that invoked it. I think that in all cases the version of Fury which runs should be the one that gets written to the configuration file. It seems like a better way to get this information into the `.bsp` configuration file would be to have the `fury` runner script determine its own path, and pass it in as a parameter on startup.

**Comment by propensive** [comment]
In fact, it is already passed in as the property `fury.home`.
