### ISSUE TITLE
new installation process

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1069]
- [x] The install directory should always be `~/.local/share/fury` or wherever `$XDG_DATA_HOME` points, and we shouldn't ask where to install to
- [x] Fury should be built as a single fat JAR
- [x] Installation should be done by Fury itself (running as `fury standalone`)
- [x] Installation should mean "including Fury on the `PATH`" and installing tab-completions; the install files will already be in-place when it's run without being installed
- [x] Installation should be into a subdirectory with the same name as version number, though the "current" version should be in a directory called `current`
- [x] install directories should contain their version number in a file (`.version`)
- [x] The installer script should be separated from the `tar.gz` bundle
- [x] The installation script should check whether Fury exists in `~/.local/share/fury` and if not, download and unpack it there, then run it (standalone) with the given arguments
- [x] The version number should be baked into the install script, and it should run the exact version that's specified in the script, installing it if necessary

This will facilitate a user experience where it's trivial to try out Fury without "installing it" (meaning modifying the user's shell startup scripts). The installer script would be a tiny download that could be included in any project, so a GitHub repository could include it if necessary.

**Comment by odisseus** [comment]
Do the licenses of all the dependencies allow repackaging them?

**Comment by propensive** [comment]
Good question... and I wonder whether Fury should (at least) make users aware of the licenses of different libraries that are included transitively...

**Comment by odisseus** [comment]
We can leave that to the user, as other build tools do. However, we should make sure that Fury itself does not violate any licenses.
