### ISSUE TITLE
allow disabling security manager

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1089]
It should be possible to run a build without the security manager, for example,
```
fury build run --disable-security-manager
```

**Comment by propensive** [comment]
This will be useful for bootstrapping.

**Comment by odisseus** [comment]
I'm not sure this is a good idea. Allowing the user to disable the security settings defeats their very purpose; it is enough to run malicious code just once to compromise the whole system.

If the layer cannot be trusted, it is dangerous to disable the security manager even temporarily. On the other hand, if the layer is trusted, there is no point in ever enabling the security manager.

I think there is a better way to reduce the burden of setting up the permissions. We could let the user   add layers to a white list. The whitelisted layers, identified by their hashes, would be run without the security manager.

**Comment by propensive** [comment]
I don't see this as a problem, at least as a temporary solution. The flag is deliberately long to mean that users wouldn't get into the habit of typing it as a matter of routine, and it's very useful for bootstrapping. In any case, it reverts back to the standard security level of, say, `sbt` or `make`.
