### ISSUE TITLE
offer tab-completion on `scalac` parameters

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#109]
If there's a way to get a list of possible tab completions from the `scala-compiler.jar` file, e.g. by invoking a `main` method with some parameters, and then parsing this output to produce a list of options relevant to that compiler, that would be ideal. Failing that, we can copy/paste the list into the source code.

**Comment by tpasternak** [comment]
oh my zsh uses hardcoded completions https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/scala/_scala
