### ISSUE TITLE
building the Fury fat JAR on Windows WSL2 takes 4 minutes

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1097]
It seems to take a full 240 seconds to build the Fury fat JAR file when running under Windows. This is about 50x slower than on Linux. Does anyone have any ideas about why?

**Comment by propensive** [comment]
This was resolved by disabling the Windows firewall for the local network, as suggested by @odisseus.

**Comment by odisseus** [comment]
I don't see how the network firewall could slow down filesystem operations such as creating and extracting archives.
