### ISSUE TITLE
replace layer hashes with IPFS base58 hashes

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1111]
This would affect the filenames of the layer files, and also references to them in layer files.

**Comment by odisseus** [comment]
```
$ ipfs add --quiet --only-hash set-up-unicorn.sh 
QmdKCW6DX3GfenTsoBpGtBiLGrSZwrWCgC8df54eY3WGsC
```

**Comment by odisseus** [comment]
https://stackoverflow.com/a/51304779

**Comment by odisseus** [comment]
https://pascalprecht.github.io/posts/content-identifiers-in-ipfs
