### ISSUE TITLE
Permission requirements in a library module

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1172]
Steps to reproduce
```
fury module add -n app -c scala/compiler -t application
# Set up sources, dependencies etc.
fury permission require -0 -C java.util.PropertyPermission -T scala.maven.version.number -A read
fury build
fury module update -t library
fury build
```
In my opinion, the first time `fury build` is invoked it should fail due to unsatisfied permission requirements, but the second time it should start compiling the module. Currently both invocations fail with permission errors.

Of course, a module marked as a library should not be executed during build, even if it has permissions and a main class. Also, if a library module depends on application modules, the permissions for those modules should be checked.

**Comment by propensive** [comment]
Yes, I think that's correct.
