### ISSUE TITLE
Fury fails when an environment variable contains a unicode character

### ISSUE THREAD

**Issue by mzarnowski** [propensive/fury-old#118]
`Nailgun` fails, when sending a unicode character using python client (it calculates the amount of bytes incorrectly).

~~Currently there is an open PR(https://github.com/scalacenter/nailgun/pull/9) waiting to be merged which should fix the issue on the `bloop/nailgun` side.~~ it is already merged in bloop, but facebook probably won't accept my PR.

to reproduce run in shell:

```bash
export X="╭─\n╰─$"
fury
```

Then, nailgun should then either hang or print an error message: 
`Server disconnected unexpectedly: [Errno 32] Broken pipe╭─`

**Comment by propensive** [comment]
I guess it would also be problematic if your project/module names contained multibyte UTF-8 characters?

**Comment by propensive** [comment]
As this is in the Nailgun script, can we just merge the change straight into the version we ship with Fury?

**Comment by mzarnowski** [comment]
we ship version from `facebook/nailgun` and there is a pull request there. But:
a) I was unable to run their "tests" and it seems these tests are also failing on their test server
b) latest changes there are from November last year with commit message `Productionize 1.0.0 release`, therefor I have some doubts if it is still actively maintained

probably we should explore other options
a) let's use nailgun from scalacenter ? (but they have customized it for bloop)
b) start maintaining our own fork of it? (a looot of complexity to understand)
c) ???

**Comment by propensive** [comment]
What is the current status of this, @marek1840? I think you were suffering from it most...

**Comment by mzarnowski** [comment]
I am not experiencing this issue anymore. Somehow my PS1 is no longer being sent. But the issue is still present, whenever someone has UTF-8 in their environment AND they are running `python 3` (since it changed the way` len(string)` works - now it returns the number of characters, not bytes - like it did in `python 2`).

to reproduce this issue run:
```bash
export X="╭─\n╰─$"
fury
```

Then, nailgun should then either hang or print an error message: 
`Server disconnected unexpectedly: [Errno 32] Broken pipe╭─`

**Comment by propensive** [comment]
I suspect that this is now fixed, since we use the native version of the Nailgun client.
