### ISSUE TITLE
color codes are displayed verbatim during installation

### ISSUE THREAD

**Issue by ArturGajowy** [propensive/fury-old#119]
Hi! Thx for the private beta release! :fireworks: :joy: 

Notice the `\e[33m*\e[0m` below:

```
artur@y510p:~$ sh fury-0.3.0.sh
...

Checking for dependencies...
 \e[33m*\e[0m Where should Fury be installed? 
```

EDIT: I've just checked and it works when I use bash instead of sh (duh!)
```
artur@y510p:~$ bash fury-0.3.0.sh
```

Maybe the instructions should mention bash?

---

I'm running elementary OS with pantheon-terminal 0.4.3 and bash:

```
artur@y510p:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 0.4.1 Loki
Release:	0.4.1
Codename:	loki

artur@y510p:~$ pantheon-terminal --version
[INFO 12:17:42.007892] Application.vala:154: Terminal version: 0.4.3
[INFO 12:17:42.007931] Application.vala:156: Kernel version: 4.15.0-43-generic
[DEBUG 12:17:42.012107] Settings.vala:163: Loading settings from schema 'org.pantheon.terminal.saved-state'
[DEBUG 12:17:42.012450] Settings.vala:163: Loading settings from schema 'org.pantheon.terminal.settings'

artur@y510p:~$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

artur@y510p:~$ echo $TERM
xterm-256color
```

**Comment by propensive** [comment]
Is this still an issue? I certainly haven't seen it recently, though I think it was always system-dependent... Any reports, @marek1840 @tpasternak?

**Comment by mzarnowski** [comment]
I haven't seen anything like this (neither when using `bash` nor `zsh` nor `sh`) but I'm running `urxvt` here on `Manjaro 18.0.3`

**Comment by ArturGajowy** [comment]
For me, the issue is in the installation instructions sent by email:

```
curl -Lo fury-0.4.0.sh https://bit.ly/hahaGotYa
sh fury-0.4.0.sh
```

They should probably say:
`bash fury-0.4.0.sh`

My assumption that it shouldn't work under `sh` might be wrong though?

**Comment by propensive** [comment]
(Sorry for the delay.)

Yes, that seems like the explanation. I'll close this issue and make sure the instructions use `bash` in future.
