### ISSUE TITLE
`fury start` is not always aware that it has started successfully

### ISSUE THREAD

**Issue by ArturGajowy** [propensive/fury-old#121]
After installing as instructed, I do the following
```
artur@y510p:~$ fury start
Fury daemon is starting............................
Starting Fury is taking longer than expected.

# ^^^ (!)
# yet, Fury seems to be up and running:

artur@y510p:~$ fury about
The project has not been specified.

# to make sure no deamon would result in different behavior:

artur@y510p:~$ fury stop
Fury daemon has shut down.
artur@y510p:~$ fury about
connect: Connection refused
```

**Comment by propensive** [comment]
I've heard reports of this before, but haven't been able to replicate it, but maybe we can do some more to diagnose it further. It would be useful to fix along with the other improvements to the runner.

**Comment by ArturGajowy** [comment]
Let me know of any info you'd like me to provide :)

**Comment by ArturGajowy** [comment]
I think I got it working by nuking my brew-installed nailgun and making sure bloop got a fresh install. Sorry for not pin-pointing the issue. My guess would be nailgun.

I see @marek1840 has just issued a fix :tada: :smile:
