### ISSUE TITLE
support sharing layers directly

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1239]
When we share a layer, it sends a request to `furore.dev` which forwards it to Pinata. But I believe IPFS has the means to resolve a file more directly by seeding it with an IP address. We could include this in the Fury URL so that someone could share a Fury URL that encodes both the hash and the IP address of the machine which hosts it, avoiding using any external server.

The command should probably be something like,
```
fury layer share --direct
```
and it would produce a URL such as,
```
fury://<base58 file hash>:<base58 IP hash>
```
though we can consider alternative formats for the URL, if that doesn't work out.

What do you think, @odisseus?

**Comment by odisseus** [comment]
First of all, the IP address is not sufficient to find an IPFS node, as it is just one part of the [multiaddr](https://github.com/multiformats/multiaddr) format. Furthermore, a multiaddr doesn't even have to include an IP address!

Second, the IP address of the host node might be inaccessible for some clients. Consider a node that is connected to two different LANs on two network interfaces. Such node would have two (or more) different multiaddr addresses, and each one would be accessible only in one of those networks. In contrast, its node ID would be the same, and any peer in any network would be able to locate the node using the command [`ipfs dht findpeer`](https://docs.ipfs.io/reference/api/cli/#ipfs-dht-findpeer).

Third, there is a more simple way to receive quick updates from a node with a known ID and accessible network address: establish a direct connection with it using the command [`ipfs swarm connect`](https://docs.ipfs.io/reference/api/cli/#ipfs-swarm-connect). I think this way is most suitable for teams of developers who work together in a common network.

If the team wants to use IPFS without sharing their build definitions with the rest of the world, they should just set up a private IPFS cluster, which [doesn't seem too hard](https://labs.eleks.com/2019/03/ipfs-network-data-replication.html).

**Comment by propensive** [comment]
I noticed in the documentation of Piñata that their API supports sending some IP addresses in order to help it discover your content faster. We actually used to do this when publishing (but I think it created some unrelated problems, so we stopped), though the idea remains. Those IP addresses of course wouldn't necessarily all be public (in general, it's a list of about 6-8 IPv4 and IPv6 addresses), nor would they be guaranteed to work, but they're a hint which could improve sharing performance.

**Comment by odisseus** [comment]
Those are the addresses of the nodes that already have the content. By sending them, you ask the Pinata node to add those nodes to its peers before downloading the content.

> If our API notices that you provided host nodes as part of your request, we’ll directly connect to those nodes before attempting to pin your content! This allows us to take advantage of the speed benefits mentioned earlier in this article by cutting out the node discovery process of pinning content.

https://medium.com/pinata/speeding-up-ipfs-pinning-through-swarm-connections-b509b1471986

In other words, this functionality is specific to Pinata, and it would work only if the user has access to their services.

**Comment by propensive** [comment]
I think that in any case, our URLs will be inconveniently long. I'll close the isuse as as non-starter.
