### ISSUE TITLE
Changes to tree sets in the layer object are not saved

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1247]
A layer with a single module is considered equal to a layer with no modules at all .This breaks most integration tests.
Here's an example of a failing test for a tree set of projects (which is part of a layer object):

```
test("Unequal projects") {
  val x = Project(ProjectId("scala"),
    TreeSet(),
    None, LicenseId("unknown"), "", None)
  val y = Project(ProjectId("scala"),
    TreeSet(Module(ModuleId("compiler"), Compiler, None, None, List(), ModuleRef("java/compiler"), TreeSet(),
      TreeSet(), TreeSet(), TreeSet(), TreeSet(), None, TreeSet(), TreeSet(), TreeSet(), false, TreeSet(), false)
    ),
    Some(ModuleId("compiler")), LicenseId("unknown"), "", None)
  //x == y //false
  TreeSet(x) == TreeSet(y) //true!
}.assert(_ == false)
```

This behaviour turned out to be caused by the way tree sets are compared: https://github.com/scala/bug/issues/10741
Tree set elements are considered equal when comparing sets if those elements are equal for the purpose of ordering, and projects are equal for the purpose of ordering if their IDs are equal.

This didn't cause any harm before, because a layer cannot have two projects with the same ID.
However, when comparing two different layers, this causes unexpected results.

**Comment by propensive** [comment]
Yes, I agree this is serious. There's an additional check before saving the layer to check whether it's actually changed (after first removing the `previous` field, which isn't a material difference). That check might stop the layer getting saved at all.

**Comment by propensive** [comment]
#1248 fixes exactly the check I mention.

**Comment by propensive** [comment]
Looks like we have at least a few passing tests now.
