### ISSUE TITLE
print help when passed no commands or `--help`

### ISSUE THREAD

**Issue by ArturGajowy** [propensive/fury-old#125]
In all of the cases below I'd expect help / short commands description to be printed:

```
artur@y510p:~/projects$ fury
connect: Connection refused
artur@y510p:~/projects$ fury --help
connect: Connection refused
artur@y510p:~/projects$ fury start
Fury daemon is starting............................
Starting Fury is taking longer than expected.
artur@y510p:~/projects$ fury --help
The project has not been specified.
artur@y510p:~/projects$ fury
The project has not been specified.
```

**Comment by propensive** [comment]
Agreed. It's usual to expect `--help` to work. I think it should be a synonym for `fury about`. Would that be reasonable?

**Comment by propensive** [comment]
Also, this suggestion assumes #126 is implemented too.

**Comment by ArturGajowy** [comment]
> I think it should be a synonym for fury about. Would that be reasonable?

Can't tell, as most likely `fury about` doesn't work as expected in my case :) See #136.

**Comment by ArturGajowy** [comment]
Now that I've worked around #136, I totally agree :)
