### ISSUE TITLE
try to start Fury deamon silently if it's not running

### ISSUE THREAD

**Issue by ArturGajowy** [propensive/fury-old#126]
When there's not a Fury running in the background, the command prints:

```
artur@y510p:~/projects$ fury
connect: Connection refused
```

I'd expect it to do the equivalent of `fury start` after detecting that fury isn't running.

**Comment by propensive** [comment]
This would be a nice improvement. Thanks for the suggestion! It should be achievable with some modifications to the `fury` script.
