### ISSUE TITLE
`fury undo` doesn't seem to work + incorrect hint

### ISSUE THREAD

**Issue by PawelLipski** [propensive/fury-old#128]
```
➜  shapeless git:(master) ✗ fury undo
Could not find the file /home/plipski/shapeless/.layer.fury.bak. Run `fury init` to create a new layer.
```

Generally doesn't work and also suggests `fury init` rather `fury layer init`.

**Comment by propensive** [comment]
Saving the `layer.fury` file should always take a backup of the previous version as `.layer.fury.bak` before writing any change. This seems to have stopped working, so might need reimplementing.

We should use a subdirectory of `.fury` to store these backups: `.fury/undo`, and each save multiple copies (ten, maybe?) so we have a larger undo buffer. Any save will need to do a few renames, and any call to `fury undo` will need to do the renames, in the opposite direction.
