### ISSUE TITLE
provide a `fury status` command

### ISSUE THREAD

**Issue by PawelLipski** [propensive/fury-old#129]
AFAIK it's now possible to see current schema&project&module separately by checking `fury schema list`, `fury project list` and `fury module list`, and it doesn't print the name of the current module but rather marks it with a `>` in the table.

It would be nice to also provide a status-like command that would print the "location" within layer, esp. since it could be baked in the command line prompt.

**Comment by propensive** [comment]
There is currently a `fury prompt` command which isn't visible in the menu. But it would be useful to have a `fury status` command, which would be a generalized version of `fury prompt` (which currently only works for `zsh`, I think.
