### ISSUE TITLE
Wrong command syntax triggers extreme memory leak

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1298]
**Steps to reproduce:**
```
fury module list -
```

**Expected behaviour:** an error message about bad command syntax
**Actual behaviour:** the Java process hogs all the CPU and memory in a matter of seconds

The top three classes by taken memory are:
* `exoskeleton.ParamMap$Parameter` (37 %)
* `exoskeleton.ParamMap$Part` (33,3 %)
* `scala.collection.immutable.$colon$colon` (29,6 %)

**Comment by propensive** [comment]
Did you get these figures from `jmap`, @odisseus?

**Comment by odisseus** [comment]
No, I used VisualVM to inspect the Fury process.
