### ISSUE TITLE
regular expression for imports only permits lowercase letters

### ISSUE THREAD

**Issue by PawelLipski** [propensive/fury-old#131]
Specifically at the step in `Supporting different compilers` section:
```
➜  tmp.ZUta7U1C23 git:(master) ✗ fury import add -i .scala:scala-2.13.0-M5 
The argument '.scala:scala-2.13.0-M5' was not a valid value for the parameter '-i/--import'.
```

For quick repro:

[getting-started.CHANGE-TO-SH.txt](https://github.com/propensive/fury/files/2760516/getting-started.CHANGE-TO-SH.txt)

And full output:

[getting-started.OUTPUT.txt](https://github.com/propensive/fury/files/2760524/getting-started.OUTPUT.txt)

**Comment by propensive** [comment]
I think the problem is with having more than one `-` in the schema name, which would suggest a problem with the regular expression.
