### ISSUE TITLE
Install fail/IPFS

### ISSUE THREAD

**Issue by veyga** [propensive/fury-old#1319]
Hello,
Not sure if this is the right place to post this issue. I am trying to install and am running into what seems to be IPFS issues. I have IPFS installed locally and running through systemd. Install was attempted with IPFS running, and with it stopped; both failed. The launcher script attempts to launch in standalone mode, so I thought the existence of IPFS local install conflicts. I uninstalled IPFS, tried the install again, which failed. Any help is appreciated.

  Writing current version (0.15.1-7-g02392cc) to a file...done    
    Cloning the Fury layer over IPFS...    
    Done    
    Compiling Fury from source...    
    Launching Fury 0.15.0 in standalone mode...    
      0.000 An unexpected error occurred:    
      0.000 antiphony.OtherException    
      0.000     at antiphony.Http$.request(httpclient.scala:77)    
      0.000     at antiphony.Http$.get(httpclient.scala:43)    
      0.000     at fury.core.Ipfs$IpfsApi.fury$core$Ipfs$IpfsApi$$getFileFromGateway(external.scala:132)    
      0.000     at fury.core.Ipfs$IpfsApi$$anonfun$get$2.$anonfun$applyOrElse$1(external.scala:76)    
      0.000     at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)    
      0.000     at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)    
      0.000     at scala.collection.immutable.List.foldLeft(List.scala:89)    
      0.000     at fury.core.Ipfs$IpfsApi$$anonfun$get$2.applyOrElse(external.scala:72)    
      0.000     at fury.core.Ipfs$IpfsApi$$anonfun$get$2.applyOrElse(external.scala:71)    
      0.000     at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)    
      0.000     at scala.util.Failure.recoverWith(Try.scala:236)    
      0.000     at fury.core.Ipfs$IpfsApi.get(external.scala:71)    
      0.000     at fury.core.Layer$.$anonfun$get$6(layer.scala:189)    
      0.000     at scala.util.Success.flatMap(Try.scala:251)    
      0.000     at fury.core.Layer$.$anonfun$get$5(layer.scala:188)    
      0.000     at scala.util.Success.flatMap(Try.scala:251)    
      0.000     at fury.core.Layer$.$anonfun$get$2(layer.scala:185)    
      0.000     at scala.Option.getOrElse(Option.scala:189)    
      0.000     at fury.core.Layer$.get(layer.scala:185)    
      0.000     at fury.core.Layer$.retrieve(layer.scala:171)    
      0.000     at fury.BuildCli.$anonfun$compile$2(build.scala:284)    
      0.000     at scala.util.Success.flatMap(Try.scala:251)    
      0.000     at fury.BuildCli.$anonfun$compile$1(build.scala:283)    
      0.000     at scala.util.Success.flatMap(Try.scala:251)    
      0.000     at fury.BuildCli.compile(build.scala:282)    
      0.000     at fury.FuryMenu$.$anonfun$menu$14(menu.scala:49)    
      0.000     at fury.core.Menu.apply(structure.scala:82)    
      0.000     at fury.core.Menu.apply(structure.scala:80)    
      0.000     at fury.FuryServer$.invoke(main.scala:49)    
      0.000     at fury.FuryServer$.$anonfun$run$2(main.scala:92)    
      0.000     at fury.core.Lifecycle$.trackThread(lifecycle.scala:82)    
      0.000     at fury.FuryServer$.run(main.scala:91)    
      0.000     at fury.FuryServer$.main(main.scala:62)    
      0.000     at fury.FuryServer.main(main.scala)    
    Failed    
    Copying Fury runner script...done    
    Downloading Nailgun C client...done    
    Downloading Nailgun Python client...done    
    Copying Procname C wrapper...done    
    Copying zsh completion script...done    
    Copying Fury icons...done    
    Creating bundle file...done    
    Rewriting Fury launcher script for local use...done    
    Installing Fury...    
    Launching Fury 0.15.1-7-g02392cc in standalone mode...    
    Error: Could not find or load main class fury.FuryServer    
    Failed

**Comment by odisseus** [comment]
This is a known problem with the recent versions, which is going to be fixed soon. Basically, if retrieving the build definitions by IPFS takes longer than a few seconds, Fury tries to get them by sending a HTTP request to an IPFS gateway, and that request always fails due to a bug in the HTTP library. 

As a workaround, you can try to pre-load all the build definitions by running this command in the repository's base directory:
```
etc/preload.sh .fury.conf
```

**Comment by odisseus** [comment]
Fix of the HTTP bug: https://github.com/propensive/antiphony/commit/75b7e7e27f9c4b2404f8e84f70acee5192567132

**Comment by veyga** [comment]
Great thx

**Comment by veyga** [comment]
Some of the tests from etc/integration fail. A few just seem to be minor details in the exact textual output. 
Other than bad-commands:#1088, are the below expected to fail at this point:
external-compiler
layer-traversal
platform
share-layer
undo

Running the suite launched a few browser tabs opening with tokens. Do I have to manually do something within github or IPFS for these to work?

thx

[etc_integration_results_1.txt](https://github.com/propensive/fury/files/4568652/etc_integration_results_1.txt)

**Comment by odisseus** [comment]
Yes, the tests that you have listed are broken at the moment. Some of them are probably outdated and should be removed. If all other tests pass and Fury is able to build itself, I'd say it's a good result.

The "bad-commands" test, on the other hand, should be passing. If it fails, that's a regression.

As far as I know, none of the integration tests require interaction from the user.

**Comment by veyga** [comment]
I'll count it as a win then
