### ISSUE TITLE
fix repo source references

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1327]
The changes to the way repos are handled has confused Fury about where its sources are. The layer needs updating.

**Comment by odisseus** [comment]
The current master [layer](https://gateway.pinata.cloud/ipfs/QmRi4LSdm2pM9CUtZiU4Tw2ugfytUpRm81jcqAuEAdRA4J) refers to the branch `issue/1185`. I'm not sure if that's related to this issue.
