### ISSUE TITLE
`layer-traversal` test fails

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1331]
The problem appears to be that every time the build runs, adding the repository `../library` causes the contents of the layer to be different every time, maybe because it's converted to an absolute path, and GitHub Actions run in a directory with a unique name each time.

If it's too problematic, we should just delete the line which prints out the IPFS hash.

**Comment by odisseus** [comment]
The test still fails, so I think this issue cannot be closed yet.

The problem with the changing layer hash is caused by the Git commit it refers to. Every time a new commit is created, it gets a unique hash (because it has a unique timestamp), which leads to differences in the layer.

**Comment by propensive** [comment]
I closed the issue, but forgot to merge the PR until now...
