### ISSUE TITLE
the `outdated-diagnostics` test seems particularly fragile

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1342]
Sometimes one of the starting/finishing logs messages gets skipped.

**Comment by odisseus** [comment]
Can you add links to any builds that are affected by this problem?

**Comment by propensive** [comment]
I'm actually not sure it's worth keeping this open. It was just a reversal of log messages, but I haven't seen the problem since I opened it, and we additionally have #1351 as a separate issue now.
