### ISSUE TITLE
introduce .fury/layer.db file

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1343]
The issues with IPFS resolving layers are getting annoying. We should store the database of used layers in a `tar.gz` file in the repository. Let's call this file `.fury/layers.db` and store everything for now. In future, we can prune any layers which aren't required to build for any of the modules in the base layer.

**Comment by odisseus** [comment]
Is it going to be just a temporary solution for this repository or something more long-lived and more general?

**Comment by propensive** [comment]
I think it's a long-term solution, but not necessarily the last iteration. I just accidentally committed it to `master` actually (instead of a PR branch).

**Comment by propensive** [comment]
And it broke all the integration tests, so I've undone it for now, but I'll try to fix the problems and merge it tomorrow.

**Comment by odisseus** [comment]
For a truly general solution, I think we should try to leverage IPNS.

**Comment by propensive** [comment]
You'll need to tell me how that would work, but this is "solving" a different problem: sharing layers without using IPFS.

The way this works is to introduce a binary "layer database" to the places that Fury checks for layers before resorting to IPFS or HTTP. The `.fury/layers.db` change is designed to be orthogonal to any other changes: it's just an additional, more direct source of resolving layers that may or may not exist for any given layer. There's a special command, `fury layer commit` which adds this layers database to the repository.
