### ISSUE TITLE
'fury restart' stops server; but doesn't restart it

### ISSUE THREAD

**Issue by veyga** [propensive/fury-old#1352]
Running 'fury restart' shuts down nailgun, but does not restart it.
#1348 exits early after shutting down, ngServer never called. 

➤ ps -e | grep fury    
➤ fury start                 
➤ ps -e | grep fury                                                                                                 
  47239 pts/0    00:00:00 fury
➤ fury restart                   
(...waited a little bit)                                                                                   
➤ ps -e | grep fury

**Comment by astefanich** [comment]
I have it fixed quickly. will try a PR

**Comment by veyga** [comment]
Thx
