### ISSUE TITLE
`fury about` prints `The project has not been specified.` instead of help

### ISSUE THREAD

**Issue by ArturGajowy** [propensive/fury-old#136]
I wasn't able to find it in docs, but judging from https://github.com/propensive/fury/issues/125#issuecomment-454755973 `fury about` should print help instead of asking for a project to act on.

```
artur@y510p:~$ fury stop
Fury daemon has shut down.

artur@y510p:~$ fury start
Fury daemon is starting............................
Starting Fury is taking longer than expected.

# the above is due to #121, ignore it

artur@y510p:~$ fury about
The project has not been specified.
(!)
```

**Comment by ArturGajowy** [comment]
#137 is likely to fix that, as my nuking of brew-installed nailgun and letting fury install it fixed this issue for me :)

**Comment by propensive** [comment]
I think I know what was causing this: it's not passing the parameters to `fury`. I think that's because of a discrepancy between different versions of the `nailgun` client. Some of them require the parameters to come after a `--`, while others don't. I think your fix will indeed work perfectly.
