### ISSUE TITLE
Remotes with equal relative paths are treated as if they were the same remote

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1370]
When the remote (which used to be called a repo) is fetched, the path where it will be stored is determined by the hash of its `ref`. The ref is just a string which can be an encoded web address (e. g. `gh:propensive/fury`) or a local directory (e. g. `../exoskeleton`). In the latter case, repos defined by a relative path might map to the same directory even if that path is resolved to different absolute paths by the layouts in which they are used.

This problem is especially visible in the integration tests, because a few of them use repositories located at `../library` (relative to the base directory of each respective test). This leads to inconsistent messages "Cloning repository at...", and makes the success of seemingly independent tests depend on the order in which they are executed. This is probably also the cause of occassional corruption of cached repositories.

**Comment by propensive** [comment]
That's some impressive investigative work! Would resolving to absolute paths be a fix, given that the full path may be different for different runs on GitHub Actions?

**Comment by odisseus** [comment]
We will have to use the absolute path when generating the name for the cache directory. I don't think it is needed to alter the definition of the remote or the way remotes are stored in the layer.
