### ISSUE TITLE
fat jar build does not produce a fat jar

### ISSUE THREAD

**Issue by veyga** [propensive/fury-old#1375]
Running a fatjar build does not produce a fat jar, but rather a normal jar.
Example: hello-world app with binary imports of scalac and commons-io
fury build run -f out

Results in 6 jars:
hello-world-app.jar
common-io-2.6.jar
scala-compiler-2.12.8.jar
scala-library-2.12.8.jar
scala-reflect-2.12.8.jar
scala-xml_2.12-1.0.6.jar

The manifest:
Manifest-Version: 1.0
Class-Path: commons-io-2.6.jar scala-compiler-2.12.8.jar scala-library-
 2.12.8.jar scala-reflect-2.12.8.jar scala-xml_2.12-1.0.6.jar
Created-By: Fury 0.15.1-42-g105112d
Main-Class: HelloWorld

A fat-jar would package all dependencies into a single jar, a relative self-contained classpath.

**Comment by veyga** [comment]
nevermind. noticed the capital F option

**Comment by propensive** [comment]
Though we ought to complain if an unrecognised flag is received...

**Comment by veyga** [comment]
should there be an option for a normal jar?

**Comment by odisseus** [comment]
In this case, the command doesn't contain unrecognized flags — the key `-f` is a `DirArg`. The command orders Fury to build a "slim" jar and place it, along with its binary dependencies, into a directory called `out`.
