### ISSUE TITLE
errors in application modules not handled correctly

### ISSUE THREAD

**Issue by PawelLipski** [propensive/fury-old#138]
At the final step in "Supporting different compilers" section (`fury build compile -s scala-2.13`), ~shapeless/core~ is rendered in strikethrough and without asterisk in `[ ]` which AFAIK indicates it's been skipped from compilation. This behavior remains so even after removing the `scala-2.12` schema.

![image](https://user-images.githubusercontent.com/3383210/51269169-1351f980-19c2-11e9-86fe-473a23d1cb74.png)

For quick repro:
[getting-started.CHANGE-TO-SH.txt](https://github.com/propensive/fury/files/2765486/getting-started.CHANGE-TO-SH.txt)

And full output:
[getting-started.OUTPUT.txt](https://github.com/propensive/fury/files/2765481/getting-started.OUTPUT.txt)

**Comment by propensive** [comment]
I think this might be a bug in the code which compiles then runs an *application* module. I think there's either a compile time or a runtime failure with `shapeless/gen`, and it's not being reported correctly.

**Comment by propensive** [comment]
Fixed with #146.
