### ISSUE TITLE
upgrade to Bloop v1.4.1

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1380]
The final release is now out.

**Comment by odisseus** [comment]
https://github.com/scalacenter/bloop/issues/1276

**Comment by propensive** [comment]
Is this affecting us too?

**Comment by odisseus** [comment]
I haven't checked yet. But Jorge [thinks](https://gitter.im/scalacenter/bloop?at=5eba840b5a0bc5394638e86f) this issue is important enough to delay the upgrade.

**Comment by propensive** [comment]
He's just released `v1.4.1`.

**Comment by propensive** [comment]
How about looking at this now, @odisseus?

**Comment by propensive** [comment]
How about looking at this now, @odisseus?
