### ISSUE TITLE
manage compiler as a binary

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1381]
When defining a compiler, such as `scala/compiler` we specify the compiler with the `-C` parameter to `module add`/`update` using Maven coordinates. We should instead manage the compiler binaries as binaries, and the `-C` parameter should take a Binary ID.

**Comment by propensive** [comment]
This would guarantee that the binary is actually included. If it's forgotten, then compilation silently hangs.

**Comment by veyga** [comment]
TBH, it would be nice if bootstrapping a scala project was a little easier.
Right now it's:
fury layer init
fury project add -n scala
fury module add -n compiler -t compiler
fury module update -C scala.lang.org:scala-compiler:2.12.8
fury binary add -b org.scala-lang:scala-compiler:2.12.8
....add your project/modules.

Referring with a binary ID would be easier; but I still think getting up and running with a hello-world in scala is little much. I am but a scrub, so don't listen to me, but I think it should be a bit easier. Maybe some set of "starter scripts", fury new-scala-project or whatever.

FYI, the cli displays a lower case c  ("--compiler -c") on autocomplete, but capital "C" is valid.

**Comment by propensive** [comment]
The bootstrapping is actually much easier than that, but it relies on published layers, and we try to avoid having the tests depend on the remote service which publishes them. My open PR to update the `hello-world` test shows a further improvement that allows the layers to be committed to a repository. It will be as simple as this if I were to publish a `hello-world` template:
```
fury layer clone -i scala/hello-world -n myproject
cd myproject
```
and everything would be set up.

As for using a binary to specify the compiler, I realised it's a non-starter because we need to support source-only compilers, e.g. building Dotty and then using it to build something. So I'm going to close this.
