### ISSUE TITLE
`project list` should show inherited projects by default

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1396]
If we can show while layers the projects come from too, that would be good.

**Comment by propensive** [comment]
And conflicts, if they exist.

**Comment by odisseus** [comment]
What is the conceptual difference between `fury project list` and `fury layer projects`?

**Comment by propensive** [comment]
`fury layer projects` was meant to show the entire universe, i.e. what I'm proposing here. I never really liked the confusion of these two commands though. I think `fury layer projects` could be removed.

**Comment by odisseus** [comment]
The interface for listing projects could look like this:
* `fury project list` for just the current layer;
* `fury project list --tree` for the current layer and all imported layers, with an additional column for the layer name.

I'm not sure what exactly you mean by conflicts, but I believe that a layer with conflicting projects should be impossible to create in the first place.
