### ISSUE TITLE
don't launch so many GitHub Actions builds

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1400]
Whenever we open a new pull request, we launch four builds. I think this was your change, @astefanich, which makes sense when the PR is coming from another repository, but do you know if it's possible to invoke it just once (for `macos` and for `ubuntu`) when a new PR is opened?

**Comment by veyga** [comment]
What are the four? I'm only seeing the `ubuntu-latest` and `macos-latest`. I can look into it, but I think that once a PR is opened, any further pushes to it will trigger it. If it's easier, it can revoke the PR trigger, and just run the tests on my fork.

**Comment by veyga** [comment]
If you click on settings, then actions, there is a list of permissions.
If the top one is selected (third party actions), that maybe be causing issues.

**Comment by propensive** [comment]
The four are {pull-request,push}*{ubuntu,macos}. It's only a superficial problem, and has both pros and cons:
- usually one of the builds is slower than the others, so we have to wait longer to get a green light on a PR
- however, usually at least one of the builds fails with a spurious error

But, if 3/4 pass, than that's a good indication that nothing is wrong, and it's just one of our issues with race conditions: #1395  or #819, probably.

**Comment by propensive** [comment]
So, I'm actually happy to leave it as it is for now. It's allowing me to merge some PRs without rerunning the tests.
