### ISSUE TITLE
Scala 3 hello-world hangs

### ISSUE THREAD

**Issue by veyga** [propensive/fury-old#1414]
I've finagled with dotty, and I can't get it up/running with fury. Even with security measures corrected (I've merged #1390), the BSP connection either hangs or is outright refused. This is the output from running the test script directly on my machine.  

Initialized an empty layer
Set current project to scala3
Set current module to compiler
Set current project to hello-world
Setting default compiler for project hello-world to scala3/compiler
Set current module to app
Starting the BSP launcher...
Opening a BSP server connection
Opening a BSP server connection
...........

**Comment by odisseus** [comment]
Please attach the BSP trace log. In order to write it, you'll have to set a configuration flag first:
```
fury config set --bsp-trace true
```
You'll have to restart Bloop to force creation of a new connection. You might also have to restart Fury and manually create the directory `.fury/logs` in your base directory. Normally these steps shouldn't be required, but there seems to be a bug.

**Comment by propensive** [comment]
Scala 3 has been working well for me in the last few days, and it's mostly good in CI. But I've seen the double `Opening a BSP server connection` message before. I don't remember what caused it, but I don't think it was in relation to Scala 3. It may represent a Bloop crash, so if you can try killing every possible instance of Java (`killall -9 java`), cleaning everything (`fury clean all`) and also `rm -rf .fury/*/` from the problematic directory. These are increasing levels of desperation, but it would be good to know which it needs.

I'd also be interested to know if Scala 2 projects compile when Scala 3 is failing.

**Comment by veyga** [comment]
Working now. definitely affected by my ipfs upgrade
