### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by veyga** [propensive/fury-old#1419]
Reinstalling fury fails after a timeout:
`0.000 java.util.concurrent.TimeoutException: Futures timed out after [120 seconds]`
....
`Error: Could not find or load main class fury.FuryServer`

I've tried deleting all install/config related directories.

Perhaps related to #1408, this looks to be attributed to ipfs
cat ipfs .fury.conf
`Error: ipfs repo needs migration`

Before this leads down an ipfs rabbit hole, any ideas, or knowledge of this issue?

**Comment by propensive** [comment]
IPFS shouldn't be required to run the build any more, so given your problems with Bloop before, I wonder if that may be the cause. Have you had Bloop compiling anything successfully in between?

The failure to find `FuryServer` probably means that the installation failed to compile correctly, but went ahead and installed an empty `tar` file anyway... I thought we had fixed this issue in the `Makefile`, but it seems like it's still there... :( Check for any error messages when running `make install`.

There's a good way out, though: the version of Fury used for bootstrapping should be more reliable. You should install it using `./fury system install`, and it will install a known-good version without needing to compile anything. If *that* isn't working, the problem most likely lies with Bloop. If you've definitely killed all running `bloop` instances, and it's still not working, the only place for the problem to be hiding is with Bloop's temporary files, and deleting the contents of `.fury/*/` should fix it. N.B. don't delete `.fury/config` or `.fury/layers.db` though.

**Comment by odisseus** [comment]
Make sure you don't use IPFS 0.5.0, as it isn't [supported](https://github.com/propensive/fury/issues/1283) yet.

**Comment by veyga** [comment]
I think it was the IPFS version
