### ISSUE TITLE
imported schema names are not validated

### ISSUE THREAD

**Issue by kubukoz** [propensive/fury-old#143]
Given `fury repo add -r gh:propensive/.scala` was ran:

`fury import add -i .scala:scala-2.1` works, but it shouldn't (there's no such version).

**Comment by PawelLipski** [comment]
I guess this is related to https://github.com/propensive/fury/issues/124

**Comment by propensive** [comment]
Yep, there's lots of validation missing. In some cases I want to allow it (probably with a warning) because you may want to refer to something which will exist later. But the exact UX is up for negotiation in this respect.

**Comment by propensive** [comment]
Closing this because schemas won't exist in their current form for much longer.
