### ISSUE TITLE
run apps inside a classloader, not a separate JVM

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1437]

**Comment by veyga** [comment]
I'm trying to figure out a resolution to #1394. Should I halt that, since changing the run behavior of apps would make work related to #1394 invalid.

**Comment by propensive** [comment]
I think that if we start running the apps in the same JVM, it might be easier to pipe `STDIN` into the apps, but I'm not 100% sure... The main reason for this is for a slight improvement in the startup time for app modules, and avoiding launching more JVMs than we need. But it may also introduce new issues for Fury by virtue of the reduced isolation...

In any case, I hope that your investigations into #1394 might help with getting `STDIN` into the process anyway.

**Comment by odisseus** [comment]
This might be related: https://github.com/scalacenter/bloop/issues/882

**Comment by propensive** [comment]
I spent a while trying to get this to work, and I'm basically giving up for now. I'll create a PR, just in case it will ever go anywhere.
