### ISSUE TITLE
OGDL serializer problems

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1458]
### 1. Sorted set of sealed trait

```scala
sealed trait X
case class X1(foo: String) extends X
case class X2(bar: Int) extends X
implicit val ord3: Ordering[X] = Ordering[String].on[X](_.toString)
```

```
could not find implicit value for evidence parameter of type fury.ogdl.OgdlWriter[scala.collection.immutable.SortedSet[fury.test.OgdlWriterTest.X]]
```

### 2. List of single-field case class
```scala
case class Wrapper(value: String)
val input = List(Wrapper("foo"), Wrapper("bar"), Wrapper("baz"))
```

```
::=[{head=["foo"],tl=[::=[{head=["bar"],tl=[::=[{head=["baz"],tl=["Nil"]}]]}]]}]
```

**Comment by propensive** [comment]
Do we need this?

**Comment by odisseus** [comment]
Not for the current state of the domain model. However, I got blocked by this deficiency when I attempted to re-implement #1382. If `X` were a general type for a binary, `X1` is a "managed binary", and `X2` is a "[supplied binary](https://github.com/propensive/fury/pull/1382#discussion_r431340183)", these types would be impossible to serialize.

**Comment by propensive** [comment]
Ok, that makes sense. Let's not worry about it for now.

**Comment by propensive** [comment]
I'm going to close this because the serializers do everything we need them to at the moment.
