### ISSUE TITLE
Bloop configuration is broken for forks of local repositories

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1462]
This is the reason why the repo-fork test fails.

**Before fork:**
```
"sources": [
    "/home/user/.cache/fury/sources/C25973C9AED0F365/src/core"
],
```

**After fork:**
```
"sources": [
    "/home/user/devel/fury/test/tmp/repo-fork/app/home/user/devel/fury/test/tmp/repo-fork/app/library-local/src/core"
],
```

This issue was caused by PR #1451.

**Comment by propensive** [comment]
That isn't too surprising. I did some work tidying up the way paths are specified, and relativized. This looks very much like an absolute path is being used as a relative one.
