### ISSUE TITLE
`fury fork` destination parameter only parses when terminated with a `/`

### ISSUE THREAD

**Issue by tpasternak** [propensive/fury-old#148]
Command

    fury repo fork -r repo1 -d /tmp/fork2

results with

    The argument '/tmp/fork2' was not a valid value for the parameter '-d/--dir'

Fury expects dir to be finished with `/` (`/tmp/fork2/`). Either this behaviour should be changed, or the error message must be more adequate.

**Comment by propensive** [comment]
Yep, this is something I've noticed before, and it's quite annoying...

**Comment by propensive** [comment]
I'm not sure forking works at all, currently...
