### ISSUE TITLE
can config changes be source-d by the installer?

### ISSUE THREAD

**Issue by kubukoz** [propensive/fury-old#152]
After installation, `fury` isn't immediately visible in $PATH. Opening a new terminal session (or calling `source ~/.yourshellconfig`) helps. The installer could do this by itself.

**Comment by propensive** [comment]
I don't think it can, can it? The installer is running in a subshell, so anything that's sourced in the installer will change the environment of the shell that's running the installer, but as soon as that exits, you'll be dumped back into the outer shell, and the changes will be lost.

We *could* output a message which tells the user to run the source command, though...

**Comment by kubukoz** [comment]
Yeah, I don't know much about that... but I guess you're right. I wonder how Homebrew works around this... I guess it only modified the path once and then puts symlinks there.

**Comment by ArturGajowy** [comment]
> We could output a message which tells the user to run the source command, though...

That's what e.g. https://sdkman.io/ did last time I installed it :)

https://sdkman.io/install

**Comment by propensive** [comment]
Ok, I'll just update the message, then. Thanks for confirming @ArturGajowy!
