### ISSUE TITLE
extract filesystem operations into a separate project

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1565]

**Comment by odisseus** [comment]
I'd like to use the interface of `fury.io.Path` outside Fury, but in my opinion it isn't mature yet. It still lacks the functions that Fury doesn't use, and the behaviour of the existing ones still changes from time to time. In fact, the last [updates](https://github.com/propensive/fury/commits/master/src/io/path.scala) to the filesystem operations happened not that long ago.

**Comment by propensive** [comment]
I've published a library called [Jovian](https://github.com/propensive/jovian) which replaces most of `fury.io`.
