### ISSUE TITLE
The layer `propensive/scala-new` does not exist on vent.dev

### ISSUE THREAD

**Issue by ckipp01** [propensive/fury-old#1573]
I was trying out fury for the first time today and following the instructions found in the [tutorial](https://github.com/propensive/fury/blob/master/doc/tutorial.md). However, it seems the layer doesn't exist?

```
❯ fury layer clone -l propensive/scala-new -f fury-sample
The layer propensive/scala-new does not exist on vent.dev
```

**Comment by kitlangton** [comment]
Using `propensive/scala` seems to work for now.

**Comment by propensive** [comment]
I'm not sure what happened here, though maybe it failed to publish when I was setting it up. Nevertheless, it's there now. :)

**Comment by athomann** [comment]
Looks like this issue has returned. Still receiving error `The layer propensive/scala-new does not exist on vent.dev`
