### ISSUE TITLE
Setup instructions not working

### ISSUE THREAD

**Issue by prolativ** [propensive/fury-old#1638]
Running
```bash
curl -Ls fury.build | sh
```
results in an error
```
sh: line 1: syntax error near unexpected token `newline'
sh: line 1: `<!DOCTYPE html>'
```
It looks like `fury.build` doesn't get properly redirected to the setup script file

**Comment by propensive** [comment]
I think the IPFS-hosted script file has stopped working. `https://fury.build` redirects to an IPFS service if you access it with `curl` or `wget`, while other browsers will redirect to `propensive.com`. It's a bit hacky, but it becomes problematic when one of the servers is down...

It shouldn't be too hard to fix, though.

**Comment by propensive** [comment]
Does it work for you now, @prolativ?

**Comment by prolativ** [comment]
Downloading the installation script still doesn't work for me when using `curl` but it seems to work with `wget`. Also running the script without arguments as in the instruction only prints
```
 INFO  Launching Fury 0.33.0 in standalone mode...
The project has not been specified.
```
But running it with `system install` args seems to work as expected

**Comment by propensive** [comment]
That probably means that my browser-sniffing code ("check for `curl` in the headers") isn't reliable. It would make much more sense for me to put the script at `get.fury.build` and leave `fury.build` as the website.

I think that behaviour is expected. IIRC the script detects whether it's being piped, and automatically defaults to `system install`, whereas running it will work like an installed `fury`. That is, one purpose of the script is to allow you to run `fury` without installing it.

This fragile code isn't a great introduction, and you're not the first person to have problems. So I think I'll make the following changes:
- move the script to `get.fury.build`
- add a comment near the top of the `fury.build` HTML page which tells you where to get the script
- try to find all the references to `curl -Ls fury.build` and replace them with `curl -Ls get.fury.build`

**Comment by propensive** [comment]
I've just fixed the GitHub readme and one other occurrence (which I'm not even sure was linked anywhere). The new domain looks like it is set up now, too.
