### ISSUE TITLE
cache bare repositories centrally

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#175]
If a number of different projects are all using the same source repositories, these could be (optionally) cached in a central location to avoid storing duplicate copies multiple times, for each project, and downloading them multiple times.

**Comment by tpasternak** [comment]
How should it look like? Should we first clone it to central cache, then to `.fury/repos` and finally to `.fury/sources`?

**Comment by propensive** [comment]
@tpasternak Sorry, I only just noticed your comment. I think we could actually just point `bloop` directly at the central repository, and not use the local one. The same is true of the sources - the hash should correspond to a unique checkout, so we don't need to have multiple copies in each project.
