### ISSUE TITLE
installer should stop old running versions of Fury before upgrading

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#187]
It's confusing when installing a new version of Fury over an old version, and running `fury about` shows the old version number.

**Comment by mzarnowski** [comment]
But if the old version is building a time consuming module?
It is basically the case of Linux updates vs Windows updates. The former can be made always which is a big selling point. 

Maybe installer can detect if fury is running and print a helpful message that it needs to be restarted? Or even prompt the user whether it should restart fury now.

**Comment by propensive** [comment]
How about `fury stop` just waits for any active processes to stop? I think we could do that.

**Comment by mzarnowski** [comment]
by "active processes" you mean `fury stop` waits until all the commands passes to `fury` are finished?

**Comment by propensive** [comment]
Yes. It's in PR #201!
