### ISSUE TITLE
please reconsider keeping the source private

### ISSUE THREAD

**Issue by johnynek** [propensive/fury-old#20]
I think build tools are hard enough to adopt that there is no real risk that you will accumulate a bunch of users who disregard the alpha status of the code.

It would be interesting to be able to see the code that is causing the issues to be closed.

**Comment by propensive** [comment]
I haven't forgotten that you asked me about this before, though I've been nervous about opening it too quickly when there's currently a lot of hype around Fury, and a bit of a gap between expectation and likely reality. I don't want to be another Google+... ;)

But the intention is to make the source code (along with a bunch of tiny dependent projects I've been working on) public on 15 November, a couple of weeks from now, and a couple of weeks from when I really kick off the private beta on Wednesday. So there will be a two-week period where people are using a version of Fury but do not have access to the source.

So, it's not long to wait now. (You're also right at the front of the queue to start using the beta later this week!)
