### ISSUE TITLE
underscore should not be allowed in module names

### ISSUE THREAD

**Issue by tpasternak** [propensive/fury-old#208]
You can add a module with underscore:

    fury module add -n my_module

But then you cannot add dependency to it from other module

    fury dependency add -M my_project/my_module

**Comment by propensive** [comment]
Good catch! I think that the underscore should not be valid in a module name.

**Comment by tpasternak** [comment]
@propensive isn't it done?

**Comment by propensive** [comment]
@tpasternak It wasn't merged until now, due to the issue with Kaleidoscope, but I found a workaround.
