### ISSUE TITLE
unexpected error when fury started without bloop in path

### ISSUE THREAD

**Issue by tpasternak** [propensive/fury-old#234]
When you start fury without bloop in PATH and then try to compile anything, you get: 

    Starting bloop compile serverAn unexpected error occurred which has been logged to /.shapeless/.fury/logs/8546876a-b041-49d6-8de1-93378f1eb629.log.
    The command '/bin/sh -c bash -c ". ~/.bashrc &&     git clone https://github.com/ArturGajowy/.shapeless.git &&     cd .shapeless &&     fury start &&     export PATH=\$HOME/.bloop:\$PATH &&     fury "' returned a non-zero code: 1

Dockerfile for this issue: https://gist.github.com/tpasternak/1c62688239d44924baf4f0a6a24f7f22

----
One of the bugs submitted in #229

**Comment by propensive** [comment]
I guess this isn't a problem any more since we're using BSP and not calling `bloop` directly. Please reopen if I've misunderstood, @tpasternak.
