### ISSUE TITLE
use https:// urls for github by default

### ISSUE THREAD

**Issue by ArturGajowy** [propensive/fury-old#238]
Creating a layer that references a git repository via a ssh-style url makes it unusable in settings where the os user doesn't have a key known to github. This is very often the case in CI environments, like travis or drone. Thu unusability is due to not being able to clone the layer:

```
artur@y510p:~/projects/rchain$ docker run -it openjdk:11-jdk 

bashroot@e1c2211aea67:/# git clone git@github.com:propensive/.scala.git
Cloning into '.scala'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
root@e1c2211aea67:/# 

```

See:
https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey
https://help.github.com/articles/error-permission-denied-publickey/#verify-the-public-key-is-attached-to-your-account

This is why, I think, https-style urls should be the default for fury layers (they allow cloning without an SSH key), and/or fury should try to convert the SSH urls to https ones when doing a layer checkout.

**Comment by propensive** [comment]
I was discussing this with @marek1840 and @tpasternak and they suggested that using `https` would not be ideal in all cases (they can probably elaborate on this). But for running in CI, it does make a lot of sense.

An idea I thought of was to have a system-wide parameter which determines whether `gh:...` repositories expand to `https` or `ssh` URLs. This would require a change to actually store the simplified names in the `layer.fury` file.

Does anyone have any thoughts on this approach? What should the default be?

**Comment by ArturGajowy** [comment]
I'm curious about the downsides of using `https` urls. @marek1840 and @tpasternak please do elaborate :)

I think `https` should be the default, as I imagine considerable amounts of potential users to not even have a GitHub account. Not to mention, running in CI should not require using any special flags.

AFAIR, ssh would only be needed for pushing to the layer repos - which most users won't be doing at all, and the others will do so infrequently. It might be that the distinction between when to use which type of url could be (related to) whether a command requires a push underneath. (So use https by default and if push is needed - use ssh first, fallback to https on auth failure - unless https auth required explicitly using a parameter?)

**Comment by tpasternak** [comment]
Hi, I only mentioned the pushing problem during the discussion. We have a forking feature in fury so theoretically someone would like to fork & push. Now I think it's rather a minor issue, as you have said definitely not frequent, so imo we can go with changing the default protocol to https

**Comment by propensive** [comment]
I'll change to `https` now.
