### ISSUE TITLE
implement BSP

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#25]
After discussions with Justin Kaeser, Fury should support BSP as a means for IDEs such as IntelliJ to get information about the build out of Fury.

**Comment by jastice** [comment]
I might want to look into this the coming weeks. Where do I start? :)

**Comment by propensive** [comment]
@jastice Maybe we should have a chat about it soon? @tpasternak is just finishing up implementing Fury as a BSP *client*, and the next step will be to implement Fury as a BSP *server*.

**Comment by jastice** [comment]
Yes, I was just about to ask about it. I have the next 2-3 weeks to work on it. Can we chat tomorrow?

**Comment by propensive** [comment]
Now that @jastice has implemented the basics of a working BSP server (thank you!), we can close this issue, and create new ones for more specific details.
