### ISSUE TITLE
verification of module references in builds

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#26]
It's possible to create links in builds to modules which do not resolve. This is fine during setup of the build (for example, you can specify that the compiler to use should be `scala/compiler` before you've imported a workspace containing the Scala compiler. But we need to check that everything resolves before attempting to run a build or publish a workspace.

References to modules which do not resolve should be marked with a bright red `!!` (or similar) until they are fixed.

**Comment by odisseus** [comment]
@propensive, which issue is duplicated by this one?
