### ISSUE TITLE
use jgit instead of `git`

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#280]
JGit can probably be used for that.

**Comment by propensive** [comment]
We need to ensure that all of the `git` commands [defined here](https://github.com/propensive/fury/blob/master/src/core/shell.scala#L52-L175) can be implemented with `jgit`.

Possibly some of these are not used any more, and can be removed.

**Comment by propensive** [comment]
It's been recommended to me that JGit is not reliable enough, so we're going to keep using the shell commands.
