### ISSUE TITLE
only the first test suite in the list is executed

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#282]
The class `fury.Tests` in core-test suggests that the test suite list may contain multiple test suites. However, I have found out that only the first suite in the list is actually executed. I believe this is caused by [this change](https://github.com/propensive/probably/commit/ff31c835ab6ea7fc7faba672a74332e7b7732df6#diff-1b4d0ae4b70a76b43f6cf12866eb4737R163) to the probably library.

**Comment by propensive** [comment]
@odisseus has a fix, and it's just waiting for me to merge it into `probably`, with a corresponding change in `fury`.
