### ISSUE TITLE
eliminate `recv: Connection reset by peer` messages

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#3]
Sometimes, noticeably during commands which call out to shell processes, Fury's UI exits reporting the message,
```
recv: Connection reset by peer
```

This appears to be a race-condition, though the exact cause is not clear. Frequently, the command output is cut short, and the error message displayed instead. It's possible that Nailgun may be involved in the interaction.

**Comment by propensive** [comment]
This issue remained mysterious for a long time, though it appears to be a bug in the nailgun client, apparenty with the native (C) version of nailgun, and the Python version, when running with either Python 2 or 3, but displaying different error messages with each.

It appears that it occurs whenever a single two-byte (or larger) UTF-8 character is returned from Fury to the Nailgun client which straddles a chunk boundary. Nailgun tries to decode the UTF-8, but fails because it receives only half a character, so it crashes. The error, from Python 3 (only) is informative: it reports a failure to decode a character "at position 2047". That sounds a lot like the last byte in a 2048-byte chunk.

It might be possible to hack the source for the Nailgun client, nailgun server or even Fury.

**Comment by propensive** [comment]
Fixed, finally!

**Comment by kubukoz** [comment]
Wow :D
