### ISSUE TITLE
publish project configuration and dependencies

### ISSUE THREAD

**Issue by ArturGajowy** [propensive/fury-old#30]
Thanks for sharing the sources! :tada: 

Can we get a list of dependencies fury uses, so that we can build the binary ourselves?

Looking at the imports, it seems to me the only non-propensive dependency seems to be the nailgun. Is that correct? Would simply checking out all projects from the organization and building them together (with nailgun) be enough for building fury?

**Comment by propensive** [comment]
You're right about the dependencies - Nailgun is the only third-party dependency. This list of dependencies is:
- Totalitarian
- Mitigation
- Optometry
- Mercator
- Eucalyptus
- Exoskeleton
- Magnolia
- Gastronomy
- Impromptu
- Annexation
- Escritoire
- Contextual
- Guillotine
- Lanifice
- Kaleidoscope

Though at least a couple of these can probably be removed when I get a chance to clean up the code.

Nevertheless, it's a deliberate decision to not make it easy to build, at least for the next week or so. The version represented by the current source has two serious bugs (which render it almost useless right now), and which I'll need to fix before sharing Fury with anyone. But once I've sent out the first few binaries to people who signed up for the beta, I'll work on making it more easily buildable. A large part of that will involve making sure the repositories for all of those dependencies are up-to-date and consistent.

So, as before, the answer is "thank you for your patience". ;)

**Comment by 2m** [comment]
After playing around with a [mill build](https://github.com/martinpallmann/fury-experimental-build/) for fury, it seems that fury depends on some code that has not been pushed to the open source repositories.

For example [`guillotine.Running`](https://github.com/propensive/guillotine/blob/0dc01d808b05b7c36478ac9284c26c19dc50ab04/src/macros/macros.scala#L111-L113) is missing `destroy`:

```
[error] /home/martynas/projects/fury-experimental-build/fury/src/core/bloop.scala:37:31: value destroy is not a member of guillotine.Running
[error]         bloopServer.foreach(_.destroy())
[error]
```

[`optometry.Optic`](https://github.com/propensive/optometry/blob/3874522cd5d4ab7c63ade4c7ae80e90eca94937f/src/core/lens.scala#L13) should have 3 type parameters instead of two:

```
[error] /home/martynas/projects/fury-experimental-build/fury/src/core/lenses.scala:39:70: wrong number of type arguments for optometry.Optic, should be 2
[error]     def apply[A, AId](id: AId)(implicit resolver: Resolver[A, AId]): Optic[SortedSet, Id, A] =
[error]
```

And implicit conversion between `guillotine.AsyncProcess` and `guillotine.Running` seems to be missin:

```
[error] /home/martynas/projects/fury-experimental-build/fury/src/core/shell.scala:84:49: type mismatch;
[error]  found   : guillotine.AsyncProcess
[error]  required: guillotine.Running
[error]       sh"sh -c 'bloop server > /dev/null'".async(_ => (), _ => ())
```

**Comment by propensive** [comment]
I'm flattered you're trying this... ;) Though it's still work-in-progress for a bit longer, as I tidy up Fury and related projects... sorry not to be able to give a better answer right now.

**Comment by martinpallmann** [comment]
I will try to build every now and then and see how far it goes.

**Comment by martinpallmann** [comment]
Thanks to @2m for the help.

**Comment by 2m** [comment]
No worries. Thank you @martinpallmann for doing the imitial hard work! :)

**Comment by propensive** [comment]
So, in case you didn't notice, it's possible to build and install Fury from source, directly from this repository now, using `make install`
