### ISSUE TITLE
always generate bsp config

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#300]
I can't see any reason why we shouldn't create `.bsp/fury.json` when we initialize the repository. I don't think it needs to be a separate command, and it's a cheap operation. Any reason not to, @jastice?

**Comment by jastice** [comment]
Generally agree. Reasons it might still need to be separate command:
* projects that have not yet created the bsp file. `fury layer init` currently overwrites an existing `layer.fury`, that might have to be changed
* generating a new `fury.json` when fury installation location changes. Eventually Fury should set up the bsp config in the user/system space anyway.

**Comment by jastice** [comment]
I think there was still the issue that after cloning a repo, there was no way to generate a bsp config except modifying the build in some arbitrary way
