### ISSUE TITLE
Consider giving UserMsg a nice toString for debugging

### ISSUE THREAD

**Issue by kubukoz** [propensive/fury-old#309]
It'd really help: right now, if you're looking at the code at a stopped breakpoint, and you have a `UserMsg` in hand, it'll only show that it's `UserMsg(some lambda)`. I believe a `toString` could be derived with a macro, and it could resolve to e.g. the code (roughly, because current macros will remove some syntactic sugar) that was used to write the instance:

```scala
UserMsg(theme => "foo bar".blah(theme))
```

might have a toString very similar to the code.

Alternatively, the messages used could be made as `object FooMsg extends UserMsg(theme => ...)`, so looking at the debugger you'd see `FooMsg` and could find its definition (and the general message format) easily.

Alternatively, toString could be just `thing.string(Theme.NoColor)`.

**Comment by propensive** [comment]
`thing.string(Theme.NoColor)` is the solution, I think.

**Comment by kubukoz** [comment]
Does this still need a PR?

**Comment by propensive** [comment]
No.
