### ISSUE TITLE
`binary remove` command should identify binaries just by artifact ID if possible

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#318]
### Setup
```
$ fury binary list
SERVICE  GROUP                         ARTIFACT              VERSION         
central  com.fasterxml.jackson.module  jackson-module-scala  2.9.7
```
### Examples that don't work but should
* Should work unless there are two binaries with the same artifact ID 
```
fury binary remove -b jackson-module-scala
```
* Should work unless there are two versions of this binary
```
$ fury binary remove -b com.fasterxml.jackson.module:jackson-module-scala
```
* Also, Fury should print an error if it was unable to identify the target binary.

**Comment by propensive** [comment]
Yes, this would be useful. It's also almost guaranteed to be a bug if the user has two different versions of the same binary in the same project, so maybe we should just index binaries by their project name?
