### ISSUE TITLE
question about using CID/multihash

### ISSUE THREAD

**Issue by sideeffffect** [propensive/fury-old#345]
I've learned that Fury stores build/ build definitions on IPFS.
So does that mean it uses [`CID`](https://github.com/multiformats/cid)/[`multihash`](https://github.com/multiformats/multihash) (originated in IPFS/IPLD) for identifying them (CID is probably the right thing here, multihash is just a component of that)?
In short, it's a way to encode the hash in a self-describing and thus future-proof way.

**Comment by propensive** [comment]
Yes, it will use IPFS's hashes, at least to begin with, and this could be generalized later.
