### ISSUE TITLE
saving JAR files does not get classes from correct directories

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#369]
Since upgrading to the latest version of Bloop, saving JAR files does not work any more.

The reason is that, for the purposes of keeping different Bloop clients isolated, the output directories specified in the Bloop configuration files are not the exact directories that are used: Bloop will create new directories with the same name, plus a suffix. Class files will be put into these new directories.

So, when saving a JAR file, for each module, Fury will need to specify this rewritten directory name instead of the one it thinks it should be using.

In order to do this, I think Fury will need to issue a BSP request to get the classpath for each module, and then use this to work out the correct output directory corresponding to each module. I suggest that this should be done when constructing the `Compilation` object, and stored in that object. I've recently modified the code to construct `Compilation`s asynchronously whenever configuration files change, and then store them in a global hashmap. (They're constructed synchronously if they're not already in the hashmap.)

**Comment by odisseus** [comment]
It keeps happening! Even with Bloop versions 1.3.0 and 1.3.2.

**Comment by odisseus** [comment]
See https://github.com/scalacenter/bsp/blob/master/docs/bsp.md#scalac-options-request

**Comment by odisseus** [comment]
This issue has been fixed by pull requests #403 and #411.
