### ISSUE TITLE
rewrite installer in Scala

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#381]
This will make it much more predictable than the current shell script. Also, we'll need to do it anyway when we start packaging Fury with itself. For now, it can be built with a scalac call in the makefile.

The installer jar will have to include all the libraries it uses, including Scala itself.

**Comment by propensive** [comment]
I'm not convinced that we can completely remove some amount of scripting from the installation. In any case, it was a lot of work to get the installer working as well as it is, and it might just waste time to try to bring a Scala version of the installer up to the same reliability. That's not to say it's not worth exploring.
