### ISSUE TITLE
Fury hangs when no source dir is set

### ISSUE THREAD

**Issue by tpasternak** [propensive/fury-old#390]
When one creates a new module:

    fury module add -n mymodule

buf forgets to set source dir, fury hangs after the compilation is started

**Comment by odisseus** [comment]
I have just checked this issue by removing the source add command from one of the integration tests. Both Fury and Bloop worked correctly and neither did hang (of course, the test failed because nothing actually got compiled).

@propensive, do we need an integration test for this issue?
