### ISSUE TITLE
Fury hangs when compiling java module

### ISSUE THREAD

**Issue by tpasternak** [propensive/fury-old#391]
``` 
 cd javamodule
 fury layer init
 fury project add -p javaproject
 fury project add -p -n javaproject
 fury module add -n javamodule
 mkdir javasrc
 fury source add -d javasrc
 touch javasrc/Hello.java
 fury direct
```

**Comment by odisseus** [comment]
The apparent hanging is probably caused by an exception in Bloop. Adding a _Scala_ compiler to the module makes the compilation succeed.

**Comment by odisseus** [comment]
Jorge suggested a way to fix this: https://gitter.im/scalacenter/bloop?at=5d84e43c56677e767a29abef
