### ISSUE TITLE
Provide templates for setting up simple projects

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#525]
In order to attract and retain newcomers, it would be good to provide a simple way to set up a typical project. Ideally it should be done by a single command.

Other build tools, like [SBT](http://www.foundweekends.org/giter8/) and [Maven](https://maven.apache.org/guides/introduction/introduction-to-archetypes.html), already have similar features.

In our case, a typical project definition might consist of a layer file identical to the one that is created by the [hello-world](https://github.com/propensive/fury/blob/master/test/passing/hello-world/script) integration test, but with a customizable project name.

We could provide a parameterized script that would generate such layer files. The script could even install the Fury application if it's missing in the user's environment.

**Comment by odisseus** [comment]
One such template is available at https://github.com/odisseus/incitement. It may be a good idea to provide more advanced templates, such as basic Akka project, basic web application etc.

**Comment by propensive** [comment]
This is implemented with the `layer clone` command.
