### ISSUE TITLE
coursier not found

### ISSUE THREAD

**Issue by hseeberger** [propensive/fury-old#54]
When trying to build a minimal Hello World example, after setting up everything like shown by Jon in the ScalaX2gether workshop, I get:

```
java.io.IOException: Cannot run program "coursier" (in directory "/Users/heiko/tmp/helloworld"): error=2, No such file or directory
```

**Comment by hseeberger** [comment]
There's a `~/.bloop/blp-coursier` which (a) is not on the PATH and (b) has the wrong name.

**Comment by rberenguel** [comment]
@hseeberger this is probably coming from bloop & coursier. Since I had coursier binary installed and on path (due to using it to build metals for emacs yesterday) it was working, but if I delete coursier (well, rename it) then I get the same error (java.io.IOException: Cannot run program "coursier").

A temporary mitigation could be to install the coursier binary to your path

```
cd somewhere_in_your_path # or just move it later
curl -L -o coursier https://git.io/coursier
chmod +x coursier
```

**Comment by hseeberger** [comment]
@rberenguel I can workaround the above issue with adding a symbolic link:

```
cd ~/bin
ln -s ~/.bloop/blp-coursier coursier
```

where everything in `~/bin` is on my `PATH`.

But then I get: 

```
java.io.IOException: Cannot run program "bloop" (in directory "/Users/heiko/tmp/hello"): error=2, No such file or directory
```

**Comment by rberenguel** [comment]
Uhm, not sure about that one @hseeberger I had bloop 1.1.0 installed before, but fury's install has changed it for 1.0.0 on my path (it's just a fine version as well) at /usr/local/bin/bloop 

Is it there for you?

**Comment by hseeberger** [comment]
This again can be solved like before:

```
ln -s ~/.bloop/bloop
```

@propensive, so I think the installer could do a better job in setting up the `PATH`.

Unfortunately I still cannot successfully compile:

```
~/tmp/hello(master ✗) fury
Using checked-out sources  in refspec master of git@github.com:propensive/base.git at /Users/heiko/tmp/hello/.fury/sources/WcnHdBF56k2xa9PjiW1mXw.
Starting bloop compile serverdone
 » hello/core   .  [!]


Output from hello/core:

connect: Connection refused
```

**Comment by rberenguel** [comment]
@hseeberger try a `bloop stop`and then `fury` (I had this issue because I had bloop running before fury)

**Comment by hseeberger** [comment]
I don't have a `/usr/local/bin/bloop`. And when I try to `bloop stop`, I get:

```
~/tmp/hello(master ✗) bloop stop
Could not connect to server 127.0.0.1:8212

Have you forgotten to start bloop's server? Run it with `bloop server`.
Check our usage instructions in https://scalacenter.github.io/bloop/
```

**Comment by rberenguel** [comment]
Then no idea. The `connection refused` should be between fury and the bloop server (bloop works as a server via nailgun as well), but why it may be refusing connections can be anything.

If you run `bloop` which version does it answer with?

**Comment by hseeberger** [comment]
It cannot connect, hence no version or anything.

**Comment by rberenguel** [comment]
Duh, I had it running, hence why it answered. And... looks like bloop stop was added for 1.1.0 but is not on 1.0.0

Killed all java processes to check, then `bloop server` can start, `bloop` (on another tab) answers with 1.0.0 but there is no stop command for 1.0.0 That explains what I have, but still no idea why with no bloop server running fury is unable to start bloop on its own without an error on start of bloop.

**Comment by propensive** [comment]
I'll take a look at this in more detail tomorrow. But just to note for now, if Fury finds `bloop` already running, it will use that version. If it doesn't, then it will start a new instance when it needs one (and will shut it down when Fury shuts down).

**Comment by propensive** [comment]
I think the updates I've made to the install script should make this work better. I'll publish a new release tomorrow.

**Comment by hseeberger** [comment]
Nice. A christmas release then 😉

**Comment by propensive** [comment]
Fingers crossed... ;)
