### ISSUE TITLE
clarify names of `add` and `delete` subcommands

### ISSUE THREAD

**Issue by rberenguel** [propensive/fury-old#55]
Add/remove sounds more natural than add/delete, but I'm not sure if it is just to me. If I'm not the only one, I guess having `remove` to alias internally to `delete` would be helpful

**Comment by propensive** [comment]
I'm against having multiple alternative names for the same command (even if one is hidden), but I'm not against changing `delete` to `remove` or `del`.

But first, what do other people thing? Does anyone prefer `delete` to `remove` (i.e. the current behavior)?

**Comment by leifwickland** [comment]
I agree that `remove` is the natural complement to `add`, analogous to `create`/`delete`. "Add" and "remove" suggest membership. 

However, reading the docs, it appears that perhaps you don't want membership.

> [`add`] may be used to create new projects and modules respectively. 

I'm tempted to offer a third opinion and say that it is `add` which should be changed to `create` and that `delete` is just fine. :-)

(Am I doing bikeshedding right?)

**Comment by propensive** [comment]
Yes, that's totally the correct way to do it. I hope some other bikeshedding experts will add (or create) some more suggestions. Anyway, I also wondered whether `create` would have been a better choice, so it's not a bad suggestion.

**Comment by ianp** [comment]
`remove` makes more sense to me, although personally I'd go with `summon` and `banish` 😈

**Comment by jeffrey-aguilera** [comment]
`unadd`

**Comment by gabro** [comment]
Embrace the bash way and use `dda`?

**Comment by tobias-johansson** [comment]
`add`/`drop`?

**Comment by marklister** [comment]
So in your talk you said something like "git like workflow"

Git's equivalent is probably `rm`

**Comment by propensive** [comment]
Ok, I'm going with `add`/`remove`. I'm not going to use `rm`, because it suggests (to me, at least) working with files.
