### ISSUE TITLE
SSH confirmation prompts 

### ISSUE THREAD

**Issue by ltbs** [propensive/fury-old#60]
I set up a clean new user account, upon attempting to run `fury repo add -r gh:propensive/base` the terminal becomes unresponsive and the following prompt was thrown inside the terminal I was running nailgun in - 

```
  NGServer 0.9.1 started on all interfaces, port 8462.
  The authenticity of host 'github.com (140.82.118.3)' can't be established.
  RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
  Are you sure you want to continue connecting (yes/no)?
```

**Comment by propensive** [comment]
In general, when Fury calls `git` or `coursier`, it assumes they they will run and terminate. But there are a variety of reasons (at least with `git`) why it may seek interactive input from the user, and will block until it gets a response. As STDIN from Nailgun is never connected to STDIN on these processes, this doesn't happen.

I'd like to hear suggestions for the best way to fix this. I can probably arrange to connect the STDIN streams, but that only makes sense in the cases where we're running processes serially. We may end up cloning Git repositories in parallel in the future.

**Comment by ltbs** [comment]
I think it would be wrong to do something like `yes | git`, or disable the checking if we care about the security.

What about something like - 
```
export GIT_SSH_COMMAND="ssh -o BatchMode=yes"
```
At least that way it should bomb out rather than prompting the user for input?
Am I likely to push modifications back to propensive/base as a normal user? If not perhaps I could get away with fetching the repo over http?

**Comment by propensive** [comment]
I've taken @ltbs's approach. Thank you for the suggestion!
