### ISSUE TITLE
running without Git user details set causes problems

### ISSUE THREAD

**Issue by ltbs** [propensive/fury-old#61]
I set up an empty new user account to test fury. 

I received the following error when attempting to run `fury repo add -r gh:propensive/base` - 

```
fatal: empty ident name (for <(null)>) not allowed  
```

**Comment by tpasternak** [comment]
It's not only about user credentials. It crashes also when you didn't asccept github's RSA keys.

**Comment by tpasternak** [comment]
RSA-keys stuff fixed in #205 
Apart from that I'd keep the current behaviour - we cannot pull anything via SSH without providing credentials. It's still possible to do it via HTTPS

**Comment by tpasternak** [comment]
Now it does not behav exactly like that but if one wants to use SSH for cloning, he needs to setup keys (it's an SSH requirement). It's still possible to use HTTPS without any configuration. We have no way to fix it as it is a git/ssh requirement.

**Comment by tpasternak** [comment]
@propensive, I think we may close this - we can't fix it in any way - SSH cloning and committing frankly require credentials.

**Comment by ArturGajowy** [comment]
IMHO fury should check that requirements for using it are met and warn if they're not. Ideally, the warning should include instructions to fix the problem.

In this case, I'd expect:

```
WARNING: The `user.name` property is not set git config, 
please set it because we'll need it to change the layer settings.
You can do this by running:

git config --global user.name "Your Username"
```

**Comment by propensive** [comment]
Fury no longer does any automatic committing, so I don't think this is a problem any more.
