### ISSUE TITLE
provide a `clean` command

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#68]
Fury creates various temporary files inside the `.fury` directory, which can be safely deleted (and Fury will recreate them), but this should be actionable through a command. The command should include options to delete:
- bloop configuration files
- repositories
- sources (sparse repos)
- bloop analysis files
- compiled classes

By default, this command should delete anything that's not used, and may be left over from previous configurations. But there should be a `--everything` option (or similar) which deletes everything, forcing it to be recreated as necessary.

**Comment by mzarnowski** [comment]
I would suggest `--all` instead of `--everything`
