### ISSUE TITLE
Generated Bloop configurations include unrelated modules in the classpath

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#728]
The classpath that gets written to the Bloop configuration seems to depend not just on the actual dependencies of the target, but on all dependencies of the entire compilation object, which may include multiple targets.

As a result, the collection of available classes for each module depends on what else is compiled at the same time, even if there's no formal dependency.

**Comment by propensive** [comment]
I think this was fixed. Please reopen if necessary, @odisseus.
