### ISSUE TITLE
Special symbols are processed by the shell twice if Nailgun is used

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#774]
## Steps to reproduce
```
$ set -o noglob
$ fury permission require -C java.util.PropertyPermission -T * -A 'read,write'
54bb16098c4d5d4efcbc86a4f7c00b9976dce7a038ca719ea693bfd1a50bf966
$ fury standalone permission require -C java.util.PropertyPermission -T * -A 'read,write'
2614b50c9de54c3c2fb2160fd103c3c3bb7838a20ac665e84fa55e3eee0a1f8d
```
```
$ fury permission list
~/devel/virtus_fury/beholder/test
HASH  CLASS                         TARGET     ACTION    
261   java.util.PropertyPermission  *          read,write
54b   java.util.PropertyPermission  README.md  read,write
```
**Expected result:** the same permission is created twice, the hashes are the same
**Actual result:** two different permissions are added, the hashes are different

**Comment by propensive** [comment]
Which permission gets added by which command?

**Comment by odisseus** [comment]
The incorrect permission (`54b`) is added by the first command, which is executed in the Nailgun server. I think pull request #777 would solve this issue, but it has also exposed [a different one](https://github.com/propensive/fury/issues/908).
