### ISSUE TITLE
Git error on compiling sources that don't exist

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#802]
## Steps to reproduce
1. Initialize an empty project
2. Add any remote repository, e. g. [`gh:scalaj/scalaj-http`](https://github.com/scalaj/scalaj-http)
3. Create a new project and module, set up the compiler etc.
4. Add a source directory from the repository that doesn't exist (e. g. for scalaj-http that could be `src/tests` instead of `src/test`).
5. Run `fury`.

**Expected result:** any sensible error message at step 4 or 5
**Actual result:** Git attempts to check out a nonexistent directory, resulting in an error similar to this one:
```
An error occurred while running: git -C ~.cache/fury/sources/bv6D0jjRKQ9tkuaOStBq2g checkout f1c150c2ec9b9a535e8b58003d965a42a001927f


error: Sparse checkout leaves no entry on working directory
```

**Comment by propensive** [comment]
I guess this doesn't happen very often because tab-completion usually helps (me, at least) complete a valid option.
