### ISSUE TITLE
use a faster version of the Nailgun client

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#84]
The Nailgun client that gets installed with Fury is the version that's written in Python. This currently works well enough, but there's a delay of what seems like about 100ms every time it's invoked, which includes tab completions and generating a command prompt (if you choose to use that). The native version of the Nailgun client is much faster, but (I think) needs to be compiled natively.

I think the C version of the Nailgun client is the one to use. We just need a good way to distribute it.

**Comment by tpasternak** [comment]
How about using native-image bulids instead of client/server? :)

**Comment by ArturGajowy** [comment]
@tpasternak I think that would complicate having Windows support, as ["Support for GraalVM on Windows is currently under development."](https://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html) :)

**Comment by tpasternak** [comment]
Oh, that's true
