### ISSUE TITLE
fast JAR file creation has been lost

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#912]
It looks like we have somehow lost Ricardo's work on parallel JAR file creation. I've no idea where this happened, but it shouldn't be too difficult to find it in the Git history. Maybe a rebase or merge went wrong somewhere in the last month?

Additionally, we should check what else got included in the same commit. If we lost this, then was anything else lost at the same time?

**Comment by odisseus** [comment]
I believe this functionality is present. If you compare the [changes](https://github.com/propensive/fury/pull/707/files#diff-eb36d1d990764b5cce02490e17cee0ca) introduced in PR #707 to the current state of the master, you'll see that most of those changes still exist.

**Comment by propensive** [comment]
Oh, you're absolutely correct. I was getting confused because I couldn't find the Apache Commons Compress JAR in the build... but it must have been in a different module. This is another reason why we need to fix #847!

**Comment by propensive** [comment]
I think this means I get to use the `invalid` label for the first time! ;)
