### ISSUE TITLE
provide more detailed output from BSP with a `--trace` option

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#941]
BSP traces are very useful for debugging, but writing them all the time (as older versions used to do) is an overkill. I think a good middle ground would be writing the trace to a user-defined output file when a special flag is present.

**Comment by propensive** [comment]
How about a flag which logs the output to the global log? The infrastructure is already there, and it would be a matter of calling `log.note(msg"...")` for each message. To reduce the amount of output, we could potentially even define a `UserMsg` serialization which prints only the interesting stuff, and highlights the content in the output file.

**Comment by odisseus** [comment]
That's not quite the same. I'd like to view the raw data as it is exchanged between Fury and the BSP server, just like the BSP plugin for IntelliJ does. Any log messages processed by Fury would be just an interpretation of that data.
