### ISSUE TITLE
The "Exit Build Notification" is not sent

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#946]
When closing a BSP connection, Fury sends [`build/shutdown`](https://github.com/build-server-protocol/build-server-protocol/blob/master/docs/specification.md#shutdown-build-request), but doesn't send [`build/exit`](https://github.com/build-server-protocol/build-server-protocol/blob/master/docs/specification.md#exit-build-notification). Apparently, Bloop doesn't like this:
```
Client in /home/virtuslab/devel/fury/.bloop disconnected with a 'SocketError' event. Cancelling tasks...
```

**Comment by propensive** [comment]
So, do you think that sending this would have been an easy fix to the various socket errors we were getting a few months ago?

**Comment by propensive** [comment]
Actually, looking at your PR, I think this was previously being sent, at least for some version of the code we were trying at some point.

**Comment by odisseus** [comment]
I don't think this bug has any major consequences, or the fix could resolve any major issue, especially with the former connection pool. The bulk of problems with the connection pool were caused by uncertainty about the lifetime of a connection, faulty pool synchronization, and maybe incorrect handling of I/O streams.
