### ISSUE TITLE
Live updates from a BSP connection are sent only to one of the clients

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#987]
## Steps to reproduce
1. Run `fury clean` so that the following tasks take noticeable time.
2. Run `fury build` and wait until the build graph appears.
3. Run `fury build` in another terminal.

**Expected behaviour:** in both terminals, graphs are updated as the build progresses
**Actual behaviour:** While the graph in the first terminal is updated, the second terminal displays an empty graph. After the first terminal reports that the build has been completed, there is a delay of a couple seconds, and the second graph gets filled very quickly.

**Comment by propensive** [comment]
Check that the second graph is processing a `flush()` to its `stdout` every time.
