### ISSUE TITLE
BSP configuration is not generated

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#993]
Although the code that generates the configuration file for BSP server discovery still exists, it is never invoked by any command. This breaks integration with IDEs.

**Comment by odisseus** [comment]
Related: #300, #310

**Comment by propensive** [comment]
I think this is fixed. We need Metals to invoke it instead of using Bloop as soon as it finds the `.bloop` directory (which is the default), but the Metals team is aware of that.
