### ISSUE TITLE
An application module is not executed if it has no source directories

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#998]
A workaround is creating an empty source directory. This is sufficient to trigger a BSP compile request and subsequent execution of the main class.

**Comment by propensive** [comment]
I think the solution should be:
1. if a module has no `source`s, then don't even attempt to compile it; either skip over it when calculating the subgraphs, or create an empty directory to keep Bloop happy
2. if someone has added a `source` but the directory contain no source files, consider this to be a build error, and refuse to compile.

These can be two separate issues, if you like.

**Comment by odisseus** [comment]
A module that has no sources at all cannot be skipped, because it might be an application module. In fact, this is the use case of "runner modules".

A module that has source directories but no sources is not always an error in the build definition — the source files might have been deleted during the watch mode session. Furthermore, I think it is up to the compiler to decide which files in the directory constitute the sources. (Yes, I remember that source file extensions are hardcoded in the build repeater, but I hope we'll be able to avoid this someday.)
